
name: Hola mundo

on: [push, pull_request]

jobs:
  hola:
    runs-on: ubuntu-latest

    steps:
      - name: LS
        run: ls -al

  other:
    runs-on: ubuntu-latest
    needs: [hola]
    steps:
    - name: Hola Mundo
      run: echo "GOO A TODO"

    - name: touch file
      run: touch hola.txt

    - name: set text
      run: echo "hola locooo tu puedes" >> hola.txt

    - name: Read file
      run: cat hola.txt 
           